### PR TITLE
spritesheet having frames of different width and height.

### PR DESCRIPTION
**Pull request by qsrahman**
If a spritesheet contains frames of different width and height it will not be rendered correctly unless the changed is made.

### CODE REVIEW

**Comment by kittykatattack** [comment]
Great catch, thanks!

**Comment by kittykatattack** [comment]
This change actual made it in to the production code for the new Advanced book that's coming out within the next month:

http://www.apress.com/advanced-game-design-with-html5-and-javascript?gtmf=s

I'd like to give you an acknowledgement in the book's preface for your help. 
Is this text OK?:

"Thanks to Sami ur Rahman Qazi for a suggested improvement on how the gotoAndStop method handles texture atlas frames of differing sizes in Chapter 4."

**Comment by qsrahman** [comment]
Thanks :+1:

**Comment by kittykatattack** [comment]
Cool, it's done :)

**Pull request merged**
